### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by DaRealSh0T** [Izzy129/slasher-ai#2]
Where's my credit? The source is stolen from my old clonesmasher github repo. It's mainly based off my source with other people's sources pasted into it. https://github.com/DaRealSh0T/Clone-Smasher/tree/382c4fa144cebf3b0a45b059a126a80e919f5a18

**Comment by Izzy129** [comment]
i didn’t make these bots, i just uploaded them on github to git clone them, although i’ll credit you in the readme, sorry!
